version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
